id: DEF5DEE2E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:24:19+00:00'
last_modified: '2022-05-27T15:19:32.877978+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    8ecd:
      image_group_id: I1PD95909
      title: བསླབ་པ་ཀུན་ལས་བཏུས་པ།
      total_pages: 1877
      order: 64
      base_file: 8ecd.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
