id: 5515bc2132b749f1a5b17b687e323cc1
initial_creation_type: ocr
source_metadata:
  volumes:
    9d536363b7494932a48092ee7ceadfea:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: བསླབ་པ་ཀུན་ལས་བཏུས་པ།
      total_pages: 1902
      volume_number: 64
